V.4.0.0 rc1
medcomdk/dk-medcom-carecommunication pull request #57
Opened 2024-06-10 15:17 UTC by tmsMedcom

@ovi-medcom 
Please review profiling: [input/fsh/MedComCareCommunication.fsh](https://github.com/medcomdk/dk-medcom-carecommunication/compare/master...v.4.0.0-rc1#diff-182c98e70f594a254d9444b61b0df627f7027b80890bcead9d5afb6204a3c2f7)
[input/fsh/MedComCareCommunicationProvenance.fsh](https://github.com/medcomdk/dk-medcom-carecommunication/compare/master...v.4.0.0-rc1#diff-b3322ff4dd8b631eeb3380df1fef737248fda26d2d24aca34dd5be3266ef8824)

And profile description: [...pagecontent/StructureDefinition-medcom-careCommunication-communication-intro.md](https://github.com/medcomdk/dk-medcom-carecommunication/compare/master...v.4.0.0-rc1#diff-e94ea6de615c983d98e8ddc18401891a188a09ce08d9e14d92811a171e9b2e06)
 and  [input/pagecontent/StructureDefinition-medcom-careCommunication-provenance-intro.md](https://github.com/medcomdk/dk-medcom-carecommunication/compare/master...v.4.0.0-rc1#diff-a084216645bdebcf8f4877f41ee6cffc447762db20f5aba07a9587dc372b9f1c) 

And example page: [input/pagecontent/examples.md](https://github.com/medcomdk/dk-medcom-carecommunication/compare/master...v.4.0.0-rc1#diff-6181737221e33af651a30a6e2690a7cb36dbf549a26a98f4a4a80f255719ad25)

All changes can be found here: https://build.fhir.org/ig/medcomdk/dk-medcom-carecommunication/branches/v.4.0.0-rc1/ 

@RikkeVestesen, please review the example page and examples, as discussed

2024-06-12 10:17 UTC, RikkeVestesen requested changes
1) https://build.fhir.org/ig/medcomdk/dk-medcom-carecommunication/branches/v.4.0.0-rc1/StructureDefinition-medcom-careCommunication-communication.html er set igennem og kommentarer er i review.

Eksemplerne er gennemgået, kommentarer er i review.

Jeg har desuden rettet lidt korrektur i index.md

Sig til, hvis du har spørgsmål :)

2024-06-17 10:31 UTC, tmsMedcom commented on input/pagecontent/examples.md
> +[2nd message](Bundle-b56549f7-ed10-422d-8088-f7222b686e46.html)
Super - Det ses ved, at der ikke er en reference til forfatteren i det payload, der indeholder bilaget.

2024-06-17 10:34 UTC, tmsMedcom commented on input/pagecontent/examples.md
> +[4th message](Bundle-c0426e3e-978f-46e8-a366-a30f27854b0a.html)
I MessageHeaderen skal du se efter, hvilken organization, der er afsender. Når du så kigger på afsender organisationen, skal elementet 'name' ikke fremgå. :)

2024-06-17 10:35 UTC, tmsMedcom commented on input/pagecontent/examples.md
> +[5th message](Bundle-d11968f5-4bdf-4b50-b146-a8e1cc890fc3.html)
Ja, nemlig. Der er en fejl i beskrivelsen. Det er PractitionerRole.code.text (code tilføjet)

2024-06-17 10:40 UTC, tmsMedcom commented on input/pagecontent/StructureDefinition-medcom-careCommunication-communication-intro.md
> -When sending a CareCommunication message it is possible to add a more specific receiver of the message, called a recipient, and a more specific sender, which can be found in the elements Communicatio
Jeg har flyttet rundt på indholdet på siden, men ser lidt voldsomt ud :)

2024-06-17 10:52 UTC, tmsMedcom commented on input/pagecontent/StructureDefinition-medcom-careCommunication-communication-intro.md
> +**Identifier:** An UUID version 4 with a reference to the assigner organisation. The assigner organisation is the organisation who assigned the UUID, which will be the same as the sender organisation
God pointe!

2024-06-17 10:54 UTC, tmsMedcom commented on input/pagecontent/index.md
Tak for hjælpen @RikkeVestesen - rigtig gode bemærkninger! :D

2024-06-18 15:12 UTC, ovi-medcom approved these changes

2024-06-18 15:31 UTC, tmsMedcom commented
@ovi-medcom thank you! Have you changed the bug or what is it?

2024-06-18 15:40 UTC, ovi-medcom commented
In the MedComMessaging IG I would have expected MedComMessagingMessageHeader  to require a MedComMessagingMessageDefinitionfhir.

When referencing a [MedComMessagingMessageDefinition] canonical "version" must be included, like "[MedComMessagingMessageDefinition.canonicalurl] | [MessageDefinition.version]]" where content in brackets are replaced by the concrete content of these elements and the two elements are  separated by the "|".

In MedComCareCommunicationMessageHeader MedComCareCommunicationMessageDefinition should be referenced instead of MessageDefinition and with the proper version 

Hope this is clear enough :-)

2024-06-18 15:46 UTC, ovi-medcom commented
Another thing we need to move to MedComMessaging IG is this valueset: https://build.fhir.org/ig/medcomdk/dk-ehmi-eer/ValueSet-ehmi-messagedefinition-use-context-code-valueset.html

The name of the valueset should be changed to something like medcom-messagedefinition-use-context-code-valueset. 
After this the reference to the eer-valueset in https://build.fhir.org/ig/medcomdk/dk-medcom-messaging/StructureDefinition-MedComMessagingMessageDefinition.html should be changed

2024-06-19 13:28 UTC, tmsMedcom commented
@ovi-medcom

> In the MedComMessaging IG I would have expected MedComMessagingMessageHeader to require a MedComMessagingMessageDefinitionfhir.
> 
I haven't made changes to the MedComMessagingIG. I guess I assumed it was good to go. But I will make the changes.

> When referencing a [MedComMessagingMessageDefinition] canonical "version" must be included, like "[MedComMessagingMessageDefinition.canonicalurl] | [MessageDefinition.version]]" where content in brackets are replaced by the concrete content of these elements and the two elements are separated by the "|".
> 
Is this what you expect? 
> In MedComCareCommunicationMessageHeader MedComCareCommunicationMessageDefinition should be referenced instead of MessageDefinition and with the proper version
> 

Is this what you expect? 
In profile: ![image](https://github.com/medcomdk/dk-medcom-carecommunication/assets/88831880/174fb9c6-c79f-4b61-acef-f617a7aaba06)

and in instance: 
![image](https://github.com/medcomdk/dk-medcom-carecommunication/assets/88831880/3ce381fd-7233-4886-8a94-bb64c1f832d0)

@

2024-06-19 13:30 UTC, tmsMedcom commented
@ovi-medcom 

> Another thing we need to move to MedComMessaging IG is this valueset: https://build.fhir.org/ig/medcomdk/dk-ehmi-eer/ValueSet-ehmi-messagedefinition-use-context-code-valueset.html
> 
> The name of the valueset should be changed to something like medcom-messagedefinition-use-context-code-valueset. After this the reference to the eer-valueset in https://build.fhir.org/ig/medcomdk/dk-medcom-messaging/StructureDefinition-MedComMessagingMessageDefinition.html should be changed

Shouldn't the terminology be kept in the terminology IG?

2024-06-21 09:19 UTC, ovi-medcom commented
You have nailed it in both answers, the responsibility of not being clear on, what you could assume, is mine :-)
Thanks!
Ready to go?

2024-06-21 09:22 UTC, tmsMedcom commented
Perfect! Yes - ready to go

2024-06-21 09:23 UTC, merged